# Generated by Django 5.2 on 2025-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('icon', models.ImageField(upload_to='', verbose_name='ایکون')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('profession', models.CharField(max_length=300, verbose_name='حرفه')),
                ('email', models.EmailField(max_length=300, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('birthday', models.DateField(max_length=20, verbose_name='تولد')),
                ('location', models.CharField(max_length=300, verbose_name='مکان تولد')),
                ('about_me', models.TextField(verbose_name='درباره من')),
                ('hobbies', models.ManyToManyField(to='home.hobby', verbose_name='علایق')),
            ],
        ),
    ]
