# Generated by Django 5.2 on 2025-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='ایکون'),
        ),
    ]
