# Generated by Django 5.2 on 2025-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hobby_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='aboout',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='توضیحات'),
        ),
    ]
