# Generated by Django 5.2 on 2025-05-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hobby_icon_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='aboout',
            new_name='description',
        ),
    ]
