# Generated by Django 5.2 on 2025-05-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
