# Generated by Django 5.2 on 2025-05-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
