# Generated by Django 5.2 on 2025-05-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_about_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات '},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'پست وبلاگ', 'verbose_name_plural': 'پست\u200c وبلاگ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی '},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'تحصیلات', 'verbose_name_plural': 'تحصیلات '},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی '},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست '},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'دیدگاه(2)', 'verbose_name_plural': 'دیدگاه(2)'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت '},
        ),
    ]
