# Generated by Django 5.2 on 2025-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_about_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'پست وبلاگ', 'verbose_name_plural': 'پست\u200cهای وبلاگ'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه درباره من', 'verbose_name_plural': 'دیدگاه\u200cهای درباره من'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'تحصیلات', 'verbose_name_plural': 'تحصیلات'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'سابقه کاری', 'verbose_name_plural': 'سابقه\u200cهای کاری'},
        ),
        migrations.AlterModelOptions(
            name='hobby',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateField(verbose_name='تولد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='بروزرسانی'),
        ),
    ]
