# Generated by Django 5.2 on 2025-06-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blogpostcomment_delete_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='image',
        ),
    ]
