# Generated by Django 5.2 on 2025-06-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_about_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcomment',
            options={'verbose_name': 'کامنت پست ها', 'verbose_name_plural': 'کامنت پست ها'},
        ),
    ]
